name: Flutter DigiNews CI/CD

# Alur kerja ini akan berjalan otomatis setiap ada push atau pull request ke branch 'main' atau 'master'
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build & Validate Flutter APK
    runs-on: ubuntu-latest

    steps:
    # 1. Mengunduh kode dari repositori GitHub ke server virtual
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Memasang komponen Java (Diperlukan untuk membuild Android/APK)
    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Memasang Flutter SDK di server virtual
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Menggunakan Flutter versi 3 terbaru yang stabil
        channel: 'stable'
        cache: true # Mengaktifkan cache agar proses build berikutnya lebih cepat

    # 4. Mengunduh semua package dependencies (http, isar, lottie, dll)
    - name: Install dependencies
      run: flutter pub get

    # 5. Menjalankan Code Generator (Build Runner) untuk Isar Database (.g.dart)
    - name: Run Build Runner Generator
      run: flutter pub run build_runner build --delete-conflicting-outputs

    # 6. Memvalidasi kualitas kode (Linter static analysis)
    - name: Analyze code syntax
      run: flutter analyze

    # 7. Membangun aplikasi menjadi berkas APK rilis dengan argumen env dev kamu
    - name: Build Release APK
      run: flutter build apk --release --flavor dev --dart-define=ENV_NAME=DEV

    # 8. Mengunggah hasil APK yang sudah jadi ke tab 'Artifacts' di GitHub agar bisa diunduh dosen
    - name: Upload Output APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: diginews-release-apk
        path: build/app/outputs/flutter-apk/app-dev-release.apk